spring:
  application:
    name: financial-hub-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  structured:
    format:
      console: ecs
server:
  shutdown: graceful
